---
title: "sys.calls()"
author: "jim"
date: 2020-07-23T21:13:14-05:00
TAGS:  ENV, sys.calls, sys.nframe
---


```{r setup,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = TRUE)
```

Before do anything, what frame # ?
```{r start}
cat("nframe = ", sys.nframe(), "\n")
```

How many levels down ?  

  -  0=GlobalEnv  
  -  chain of functions, a() calls b() ...  
```{r nframe_levels}

a  <- function() {
  cat("nframe = ", sys.nframe() , "\n")
  b()
}

b   <- function(){ 
  cat("nframe = ", sys.nframe() , "\n")
  print(paste0("Called from ", sys.call()))
  c()
}

c  <- function() {
  cat("nframe = ", sys.nframe(), "\n")
  print(paste0("Called from ", sys.call()))
  #cat("called from ", sys.call(), "\n")
  #sys.calls()
}

cat("nframe = ", sys.nframe(), "\n")

f  <- function() a()
f()
```

recursive!
```{r loop, eval=FALSE   }
cat("nframe = ", sys.nframe(), "\n")
a  <- function() {
  if (sys.nframe() == 9) return()
  cat("nframe = ", sys.nframe(), "\n")
  a()
}
a()
```

```{r render, eval=FALSE, include = FALSE     }
rmarkdown::render(
   "/home/jim/code/hugo_projects/blog/content/post/0010_sys_calls.Rmd",
   output_format = "html_document",
   output_file = "~/Downloads/print_and_delete/out.html")

   # output_format = "pdf_document",
   # output_file= "~/Downloads/print_and_delete/out.pdf")
```



